/**
 * Copyright 2009 Sandia Corporation. Under the terms of Contract DE-AC04-94AL85000 with Sandia
 * Corporation, the U.S. Government retains certain rights in this software.
 * 
 * BSD Open Source License.
 * 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without modification, are permitted
 * provided that the following conditions are met:
 * 
 * - Redistributions of source code must retain the above copyright notice, this list of conditions
 * and the following disclaimer.
 * 
 * - Redistributions in binary form must reproduce the above copyright notice, this list of
 * conditions and the following disclaimer in the documentation and/or other materials provided with
 * the distribution.
 * 
 * - Neither the name of Sandia National Laboratories nor the names of its contributors may be used
 * to endorse or promote products derived from this software without specific prior written
 * permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY
 * WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package gov.sandia.gmp.surfacewavepredictor;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.util.Arrays;
import java.util.Scanner;
import gov.sandia.geotess.GeoTessException;
import gov.sandia.geotess.GeoTessGrid;
import gov.sandia.geotess.GeoTessMetaData;
import gov.sandia.geotess.GeoTessModel;
import gov.sandia.geotess.GeoTessUtils;
import gov.sandia.geotess.Profile;
import gov.sandia.gmp.util.globals.Globals;
import gov.sandia.gmp.util.io.InputStreamProvider;
import gov.sandia.gmp.util.numerical.vector.EarthShape;

/**
 * This is a LibCorr3D extension of the GeoTessModel for use by LibCorr3D. Specific capabilities,
 * beyond those of the base class, include acting as a metadata container for various additional
 * descriptive strings, and to provide a home for the overloaded functions
 * GeoTessModel::loadModelBinary(...) and GeoTessModel::loadExtraData(...) binary read functions.
 * <p>
 * This class can read libcorr2d surfaces generated by kbcit and convert them into libcorr3d models
 * on-the-fly.
 */
public class GeoTessModelSurfaceWaves extends GeoTessModel {

  private double[] periods;

  private int formatVersion;

  // the phase that this model supports is stored in getMetaData().getProperties().get("phase");

  /**
   * Classes that extend GeoTessModel must override this method and populate their 'extra' data with
   * shallow copies from the model specified in the parameter list.
   * 
   * @param other the other model from which to copy extra data
   * @throws Exception
   */
  @Override
  public void copyDerivedClassData(GeoTessModel other) throws Exception {
    super.copyDerivedClassData(other);
    getMetaData().getProperties().put("phase", other.getMetaData().getProperties().get("phase"));
    this.periods = ((GeoTessModelSurfaceWaves) other).periods.clone();
  }

  protected GeoTessModelSurfaceWaves() {
    super();
  }

  public GeoTessModelSurfaceWaves(File inputFile, String relativeGridPath) throws IOException {
    super(inputFile, relativeGridPath);
  }

  public GeoTessModelSurfaceWaves(File inputFile) throws IOException {
    super(inputFile, "");
  }

  public GeoTessModelSurfaceWaves(String inputFile, String relativeGridPath) throws IOException {
    super(inputFile, relativeGridPath);
  }

  public GeoTessModelSurfaceWaves(String inputFile) throws IOException {
    super(inputFile, "");
  }

  /**
   * Parameterized constructor, specifying the grid and metadata for the model. The grid is
   * constructed and the data structures are initialized based on information supplied in metadata.
   * The data structures are not populated with any information however (all Profiles are null). The
   * application should populate the new model's Profiles after this constructor completes.
   * 
   * <p>
   * Before calling this constructor, the supplied MetaData object must be populated with required
   * information by calling the following MetaData methods:
   * <ul>
   * <li>setDescription()
   * <li>setLayerNames()
   * <li>setAttributes()
   * <li>setDataType()
   * <li>setLayerTessIds() (only required if grid has more than one multi-level tessellation)
   * <li>setOptimization() (optional: defaults to SPEED)
   * </ul>
   * 
   * @param gridFileName String name of file from which to load the grid.
   * @param metaData MetaData the new GeoTessModel instantiates a reference to the supplied
   *        metaData. No copy is made.
   * @throws IOException
   */
  public GeoTessModelSurfaceWaves(String gridFileName, GeoTessMetaData metaData)
      throws IOException {
    super(gridFileName, metaData);
  }

  /**
   * Parameterized constructor, specifying the grid and metadata for the model. The grid is
   * constructed and the data structures are initialized based on information supplied in metadata.
   * The data structures are not populated with any information however (all Profiles are null). The
   * application should populate the new model's Profiles after this constructor completes.
   * 
   * <p>
   * Before calling this constructor, the supplied MetaData object must be populated with required
   * information by calling the following MetaData methods:
   * <ul>
   * <li>setDescription()
   * <li>setLayerNames()
   * <li>setAttributes()
   * <li>setDataType()
   * <li>setLayerTessIds() (only required if grid has more than one multi-level tessellation)
   * <li>setOptimization() (optional: defaults to SPEED)
   * </ul>
   * 
   * @param grid a reference to the GeoTessGrid that will support this GeoTessModel.
   * @param metaData MetaData the new GeoTessModel instantiates a reference to the supplied
   *        metaData. No copy is made.
   * @throws GeoTessException if metadata is incomplete.
   * @throws IOException
   */
  public GeoTessModelSurfaceWaves(GeoTessGrid grid, GeoTessMetaData metaData)
      throws GeoTessException, IOException {
    super(grid, metaData);
  }

  public GeoTessModelSurfaceWaves(GeoTessModel geotessModel) throws GeoTessException, IOException {
    this(geotessModel.getGrid(), geotessModel.getMetaData());
    for (int v = 0; v < geotessModel.getProfiles().length; ++v) {
      Profile[] pa = geotessModel.getProfiles(v);
      for (int layer = 0; layer < pa.length; ++layer)
        setProfile(v, layer, pa[layer]);
    }
    // set the base class model file format to the latest version
    getMetaData().setModelFileFormat(3);

    // set the derived class file format.
    formatVersion = 1;
  }

  public GeoTessModelSurfaceWaves(InputStreamProvider<File> fileLoader)
      throws GeoTessException, IOException {
    this();
  }

  /**
   * Overridden IO method.
   * 
   * @throws IOException
   * @throws GeoTessException
   */
  @Override
  protected void loadModelBinary(DataInputStream input, String inputDirectory,
      String relGridFilePath) throws GeoTessException, IOException {
    super.loadModelBinary(input, inputDirectory, relGridFilePath);
    Globals.readString(input); // classname
    formatVersion = input.readInt();

    if (formatVersion == 1) {
      int nperiods = input.readInt();
      periods = new double[nperiods];
      for (int i = 0; i < nperiods; ++i)
        periods[i] = input.readDouble();
    } else
      throw new GeoTessException(
          "Do not know how to load GeoTessModelSurfaceWaves version " + formatVersion);
  }

  /**
   * Overridden IO method.
   */
  @Override
  protected void writeModelBinary(DataOutputStream output, String gridFileName) throws IOException {
    // call super class to write standard model information to binary file.
    super.writeModelBinary(output, gridFileName);

    GeoTessUtils.writeString(output, this.getClass().getSimpleName());
    output.writeInt(formatVersion);

    if (formatVersion == 1) {
      output.writeInt(periods.length);
      for (int i = 0; i < periods.length; ++i)
        output.writeDouble(periods[i]);
    }
  }

  /**
   * Overridden IO method.
   */
  @Override
  protected void loadModelAscii(Scanner input, String inputDirectory, String relGridFilePath)
      throws GeoTessException, IOException {
    throw new UnsupportedOperationException(
        "Code to load GeoTessModelSurfaceWaves in ascii format never written.");
  }

  /**
   * Overridden IO method.
   */
  @Override
  protected void writeModelAscii(Writer output, String gridFileName) throws IOException {
    throw new UnsupportedOperationException(
        "Code to write GeoTessModelSurfaceWaves in ascii format never written.");
  }

  @Override
  public String toString() {
    StringBuffer buf = new StringBuffer(super.toString());
    buf.append(String.format(
        "GeoTessModelSurfaceWaves data:%nformatVersion = %d%nPhase = %s%n"
            + "N Periods = %d%nperiods = %s%n",
        formatVersion, getPhase(), periods.length,
        Arrays.toString(periods).replace("[", "").replace("]", "")));

    return buf.toString();
  }

  /**
   * Set the EarthShape object that is to be used to convert between [lat, lon, depth] and
   * [unitVector, radius]. If the EarthShape of this model and the specified earthShape involve
   * different earthRadii as a function of latitude, then the radii in this model will be
   * stretched/compressed to be compatible with the new earthShape.
   * 
   * @return returns true if the radii of the model were stretched / compressed.
   * @throws GeoTessException
   */
  @Override
  public boolean setEarthShape(EarthShape earthShape) throws GeoTessException {
    return super.setEarthShape(earthShape);
  }

  /**
   * Get the phase string.
   */
  public String getPhase() {
    return getMetaData().getProperties().get("phase");
  }

  /**
   * Set the seismic phase.
   */
  public GeoTessModelSurfaceWaves setPhase(String phase) {
    getMetaData().getProperties().put("phase", phase);
    return this;
  }

  public int getFormatVersion() {
    return formatVersion;
  }

  public void setFormatVersion(int formatVersion) {
    this.formatVersion = formatVersion;
  }

  /**
   * Retrieve a reference to the periods supported by this model
   * 
   * @return
   */
  public double[] getPeriods() {
    return periods;
  }

  /**
   * Set the periods supported by this model.
   * 
   * @param periods
   * @throws Exception if the number of periods is not equal to the number of model attributes.
   */
  public void setPeriods(double[] periods) throws Exception {
    if (periods.length != getMetaData().getNAttributes())
      throw new Exception(String.format(
          "Number periods specified (%d) is not equal "
              + "to the number of attributes in the model (%d)",
          periods.length, getMetaData().getNAttributes()));
    this.periods = periods.clone();
  }

}
